### ISSUE TITLE
i am having some error at server console

### ISSUE THREAD

**Issue by rorschach217** [cesarve77/simple-chat#2]
my code is like below
{{>SimpleChatWindow roomId=roomID username=name}}
name and roomID is helpers returning string.
name : Meteor.user().username;
roomID : random generated 10 character string

and in configuration file this configuratoin saved
SimpleChat.configure ({
    limit: 10,
    beep: false,
    showViewed: true,
    showReceived: true,
    showJoined: true,
    publishChats: function(roomId, limi){
        return false;
    }
});

when sending message it gives error on console.
I20160309-12:48:36.188(5.5)? hi OCHNZH9aPa gyanAdmin null gyanAdmin
I20160309-12:48:36.973(5.5)? Exception while invoking method 'SimpleChat.messageViewed' TypeError: Cannot read property 'usernames' of undefined
I20160309-12:48:36.974(5.5)?     at [object Object].Meteor.methods.SimpleChat.messageViewed (methods_server.js:78:39)
I20160309-12:48:36.974(5.5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160309-12:48:36.980(5.5)?     at livedata_server.js:708:19
I20160309-12:48:36.980(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160309-12:48:36.980(5.5)?     at livedata_server.js:706:40
I20160309-12:48:36.981(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160309-12:48:36.981(5.5)?     at livedata_server.js:704:46
I20160309-12:48:36.982(5.5)?     at tryCallTwo (C:\Users\rorschach217\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:45:5)
I20160309-12:48:36.982(5.5)?     at doResolve (C:\Users\rorschach217\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:171:13)
I20160309-12:48:36.982(5.5)?     at new Promise (C:\Users\rorschach217\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:65:3)
I20160309-12:48:37.019(5.5)? received
I20160309-12:48:37.830(5.5)? Exception while invoking method 'SimpleChat.messageReceived' TypeError: Cannot read property 'usernames' of undefined
I20160309-12:48:37.831(5.5)?     at [object Object].Meteor.methods.SimpleChat.messageReceived (methods_server.js:25:41)
I20160309-12:48:37.831(5.5)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160309-12:48:37.832(5.5)?     at livedata_server.js:708:19
I20160309-12:48:37.832(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160309-12:48:37.833(5.5)?     at livedata_server.js:706:40
I20160309-12:48:37.833(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160309-12:48:37.833(5.5)?     at livedata_server.js:704:46
I20160309-12:48:37.834(5.5)?     at tryCallTwo (C:\Users\rorschach217\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:45:5)
I20160309-12:48:37.834(5.5)?     at doResolve (C:\Users\rorschach217\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:171:13)
I20160309-12:48:37.835(5.5)?     at new Promise (C:\Users\rorschach217\AppData\Local.meteor\packages\promise\0.5.1\npm\node_modules\meteor-promise\node_modules\promise\lib\core.js:65:3)

**Comment by cesarve77** [comment]
Hi, I can't copy the issue, but I see in your code:

 publishChats: function (roomId, limit) {
        return **false**;
    },

and have to be:

 publishChats: function (roomId, limit) {
        return **true**;
    },

make the fix, try again, and if the error continue, please send a gist o repo where i can reproduce the issue

bye

**Comment by cesarve77** [comment]
Hi, any notice?

**Comment by cesarve77** [comment]
no info,feel free to reopen

**Comment by cesarve77** [comment]
no info,feel free to reopen
